trigger:
  - master

variables:
  CIBW_BUILD: cp36-* cp37-* cp38-*
  CIBW_BEFORE_BUILD: python -m pip install --upgrade pip

jobs:
- job: Linux_Build
  pool: {vmImage: 'ubuntu-latest'}
  steps: 
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6'}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7'}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8'}}
    - bash: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel numpy
        cibuildwheel --output-dir wheelhouse .
        python setup.py sdist
        cp dist/*.gz wheelhouse/.
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}

- job: MacOS_Build
  pool: {vmImage: 'macos-latest'}
  steps: 
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6'}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7'}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8'}}
    - bash: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel numpy
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}

- job: Windows_Build
  pool: {vmImage: 'windows-latest'}
  steps:
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x64}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x64}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8', architecture: x64}}
    - bash: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel numpy
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
